CREATE EXTENSION pgcrypto;
CREATE EXTENSION plpython3u;

ALTER DEFAULT PRIVILEGES REVOKE EXECUTE ON FUNCTIONS FROM public;

ALTER DATABASE spdv SET timezone TO 'America/Sao_Paulo';

CREATE USER spdv_app WITH PASSWORD 'spdv2021';
